COLUMNS:
  Gender: object                            
  Customer Type: object                      
  Age: int                               
  Type of Travel: object                      
  Class: object                 
  Flight Distance: int64                  
  Inflight wifi service: int64       
  Departure/Arrival time convenient: int64  
  Ease of Online booking: int64  
  Gate location: int64  
  Food and drink: int64  
  Online boarding: int64  
  Seat comfort: int64  
  Inflight entertainment: int64  
  On-board service: int64  
  Leg room service: int64  
  Baggage handling: int64  
  Checkin service: int64  
  Inflight service: int64  
  Cleanliness: int64  
  Arrival Delay in Minutes: float64

  TARGET_COLUMN:
    name: satifsfaction