artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Subash7Lingden/repository-cat-vs-dog/raw/main/passenger%20satisfaction.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/train.csv
  STATUS_FILE: artifacts/data_validation/status.txt